# you will need at least docker-compose version 1.7.1
version: '2'
services:
  node:
    image: icadariu/priv:node
    container_name: nodeapp
    links:
      - mongo
    volumes:
      - $PWD/yc-news-mail:/data
    working_dir: /data
    command: npm start
  mongo:
    image: icadariu/priv:mongo
    container_name: mongo
    volumes:
      - $PWD/mongodb:/data
    expose:
      - 27017
